/**
 * The pricing card must say what the product enforces.
 *
 * The front page listed its three plans as literals, under a comment claiming "the quotas
 * below are the values in the plans table, which is what entitlementCheck reads at request
 * time, so the page and the enforcement cannot disagree". They were not the values in the
 * table, they were typed next to that sentence, and the two could drift without anything
 * noticing. An earlier version of the same block advertised a Slack channel and an SLA that
 * did not exist.
 *
 * So the page now reads src/data/plans.json, and this script is the only thing that writes
 * it, from public.plans. Same arrangement as calibration.json, for the same reason: a figure
 * on the page can only be a figure that is stored.
 *
 *   bun scripts/sync-plans.ts          write src/data/plans.json
 *   bun scripts/sync-plans.ts --check  exit non-zero if the file is stale
 */
import { writeFileSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const OUT = resolve(import.meta.dir, "../src/data/plans.json");

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required.");
  process.exit(1);
}

const res = await fetch(`${url}/rest/v1/plans?select=*&active=is.true&order=sort_order.asc`, {
  headers: { apikey: key, authorization: `Bearer ${key}` },
});
if (!res.ok) {
  console.error(`plans query failed: HTTP ${res.status}`);
  process.exit(1);
}

const rows = (await res.json()) as Record<string, unknown>[];
if (rows.length === 0) {
  console.error("::error::public.plans has no active rows. There is nothing to publish.");
  process.exit(1);
}

const money = (cents: number) =>
  cents % 100 === 0 ? `$${cents / 100}` : `$${(cents / 100).toFixed(2)}`;

// stripe_price_id is deliberately not published here. It is set by hand in the live project
// and has no seed in any migration, so this file cannot know whether a plan is purchasable.
// The page therefore shows the button and createCheckoutSession reports the truth at click
// time ("That plan is not purchasable yet"), rather than the page guessing and being wrong in
// whichever direction the guess went.
const next = {
  _comment:
    "Generated by scripts/sync-plans.ts from the plans table. Do not hand-edit. The public pricing card reads from this file, so what the page advertises can only ever be what the product enforces.",
  _source: "public.plans, active rows ordered by sort_order",
  plans: rows.map((r) => ({
    id: r.id,
    name: r.name,
    price: money(Number(r.price_cents)),
    tagline: r.tagline,
    features: r.features,
  })),
};

const serialised = JSON.stringify(next, null, 2) + "\n";

if (process.argv.includes("--check")) {
  const current = readFileSync(OUT, "utf8");
  if (current !== serialised) {
    console.error("::error::src/data/plans.json is stale. Run bun scripts/sync-plans.ts");
    process.exit(1);
  }
  console.log("plans.json matches the plans table.");
} else {
  writeFileSync(OUT, serialised);
  console.log(`Wrote ${OUT} from ${rows.length} active plan(s).`);
}
