/**
 * Outcome E: a published number must be traceable to a stored observation.
 *
 * The calibration figures on the front page are the product's strongest claim, so they are
 * not typed into the page. They are read from src/data/calibration.json, and this script is
 * the only thing that writes that file, from the most recent row of golden_eval_runs.
 *
 * Run it after any new evaluation. If the page and the table ever disagree, the check in
 * scripts/check-geo.ts fails the build rather than letting the site publish a figure nobody
 * measured.
 *
 *   bun scripts/sync-calibration.ts          write src/data/calibration.json
 *   bun scripts/sync-calibration.ts --check  exit non-zero if the file is stale
 */
import { writeFileSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const OUT = resolve(import.meta.dir, "../src/data/calibration.json");

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required.");
  process.exit(1);
}

const res = await fetch(`${url}/rest/v1/golden_eval_runs?select=*&order=created_at.desc&limit=1`, {
  headers: { apikey: key, authorization: `Bearer ${key}` },
});
if (!res.ok) {
  console.error(`golden_eval_runs query failed: HTTP ${res.status}`);
  process.exit(1);
}

const rows = (await res.json()) as Record<string, unknown>[];
if (rows.length === 0) {
  // No row means no measurement. Publishing the previous file would be publishing a figure
  // with nothing behind it, so this fails rather than silently keeping the old numbers.
  console.error("::error::golden_eval_runs is empty. There is no calibration figure to publish.");
  process.exit(1);
}

const r = rows[0];
const next = {
  _comment:
    "Generated by scripts/sync-calibration.ts from the golden_eval_runs table. Do not hand-edit. Every calibration figure shown on the public site reads from this file, so a number on the page can only ever be a number that was measured and stored.",
  _source: `public.golden_eval_runs, row ${r.id}`,
  calibration_version: r.calibration_version,
  split: r.split,
  n: r.n,
  precision_at_gate: r.precision_at_gate,
  precision_wilson_low: r.precision_wilson_low,
  recall_gtin: r.recall_gtin,
  adversarial_rejection: r.adversarial_rejection,
  ece: r.ece,
  measured_at: String(r.created_at).slice(0, 10),
};

const serialised = JSON.stringify(next, null, 2) + "\n";

if (process.argv.includes("--check")) {
  const current = readFileSync(OUT, "utf8");
  if (current !== serialised) {
    console.error(
      "::error::src/data/calibration.json is stale. Run bun scripts/sync-calibration.ts",
    );
    process.exit(1);
  }
  console.log("calibration.json matches golden_eval_runs.");
} else {
  writeFileSync(OUT, serialised);
  console.log(`Wrote ${OUT} from run ${r.calibration_version} (n=${r.n}).`);
}
