/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TakedownRouteImport } from './routes/takedown'
import { Route as ReadabilityRouteImport } from './routes/readability'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhyIndexRouteImport } from './routes/why.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as WhyReasonRouteImport } from './routes/why.$reason'
import { Route as DocsWebhooksRouteImport } from './routes/docs.webhooks'
import { Route as DocsRateLimitsRouteImport } from './routes/docs.rate-limits'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsMcpRouteImport } from './routes/docs.mcp'
import { Route as DocsErrorsRouteImport } from './routes/docs.errors'
import { Route as ApiTakedownRouteImport } from './routes/api/takedown'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCheckRouteImport } from './routes/api/check'
import { Route as ApiCaptureRouteImport } from './routes/api/capture'
import { Route as AboutBotRouteImport } from './routes/about.bot'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as DocsApiResolveProductRouteImport } from './routes/docs.api.resolve-product'
import { Route as DocsApiReadProductRouteImport } from './routes/docs.api.read-product'
import { Route as ApiV1Resolve_productRouteImport } from './routes/api/v1/resolve_product'
import { Route as ApiV1Report_outcomeRouteImport } from './routes/api/v1/report_outcome'
import { Route as ApiV1Read_productRouteImport } from './routes/api/v1/read_product'
import { Route as ApiV1Compare_productsRouteImport } from './routes/api/v1/compare_products'
import { Route as ApiV1Brief_productRouteImport } from './routes/api/v1/brief_product'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as AuthenticatedDashboardWebhooksRouteImport } from './routes/_authenticated/dashboard.webhooks'
import { Route as AuthenticatedDashboardWaitlistRouteImport } from './routes/_authenticated/dashboard.waitlist'
import { Route as AuthenticatedDashboardUsageRouteImport } from './routes/_authenticated/dashboard.usage'
import { Route as AuthenticatedDashboardMetricsRouteImport } from './routes/_authenticated/dashboard.metrics'
import { Route as AuthenticatedDashboardKeysRouteImport } from './routes/_authenticated/dashboard.keys'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TakedownRoute = TakedownRouteImport.update({
  id: '/takedown',
  path: '/takedown',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadabilityRoute = ReadabilityRouteImport.update({
  id: '/readability',
  path: '/readability',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyIndexRoute = WhyIndexRouteImport.update({
  id: '/why/',
  path: '/why/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const WhyReasonRoute = WhyReasonRouteImport.update({
  id: '/why/$reason',
  path: '/why/$reason',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsWebhooksRoute = DocsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRateLimitsRoute = DocsRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMcpRoute = DocsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => DocsRoute,
} as any)
const DocsErrorsRoute = DocsErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DocsRoute,
} as any)
const ApiTakedownRoute = ApiTakedownRouteImport.update({
  id: '/api/takedown',
  path: '/api/takedown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckRoute = ApiCheckRouteImport.update({
  id: '/api/check',
  path: '/api/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaptureRoute = ApiCaptureRouteImport.update({
  id: '/api/capture',
  path: '/api/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBotRoute = AboutBotRouteImport.update({
  id: '/about/bot',
  path: '/about/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const DocsApiResolveProductRoute = DocsApiResolveProductRouteImport.update({
  id: '/api/resolve-product',
  path: '/api/resolve-product',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiReadProductRoute = DocsApiReadProductRouteImport.update({
  id: '/api/read-product',
  path: '/api/read-product',
  getParentRoute: () => DocsRoute,
} as any)
const ApiV1Resolve_productRoute = ApiV1Resolve_productRouteImport.update({
  id: '/api/v1/resolve_product',
  path: '/api/v1/resolve_product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Report_outcomeRoute = ApiV1Report_outcomeRouteImport.update({
  id: '/api/v1/report_outcome',
  path: '/api/v1/report_outcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Read_productRoute = ApiV1Read_productRouteImport.update({
  id: '/api/v1/read_product',
  path: '/api/v1/read_product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Compare_productsRoute = ApiV1Compare_productsRouteImport.update({
  id: '/api/v1/compare_products',
  path: '/api/v1/compare_products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Brief_productRoute = ApiV1Brief_productRouteImport.update({
  id: '/api/v1/brief_product',
  path: '/api/v1/brief_product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardWebhooksRoute =
  AuthenticatedDashboardWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardWaitlistRoute =
  AuthenticatedDashboardWaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsageRoute =
  AuthenticatedDashboardUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMetricsRoute =
  AuthenticatedDashboardMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardKeysRoute =
  AuthenticatedDashboardKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/readability': typeof ReadabilityRoute
  '/takedown': typeof TakedownRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/about/bot': typeof AboutBotRoute
  '/api/capture': typeof ApiCaptureRoute
  '/api/check': typeof ApiCheckRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/takedown': typeof ApiTakedownRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/rate-limits': typeof DocsRateLimitsRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/why/$reason': typeof WhyReasonRoute
  '/docs/': typeof DocsIndexRoute
  '/why/': typeof WhyIndexRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/dashboard/metrics': typeof AuthenticatedDashboardMetricsRoute
  '/dashboard/usage': typeof AuthenticatedDashboardUsageRoute
  '/dashboard/waitlist': typeof AuthenticatedDashboardWaitlistRoute
  '/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/brief_product': typeof ApiV1Brief_productRoute
  '/api/v1/compare_products': typeof ApiV1Compare_productsRoute
  '/api/v1/read_product': typeof ApiV1Read_productRoute
  '/api/v1/report_outcome': typeof ApiV1Report_outcomeRoute
  '/api/v1/resolve_product': typeof ApiV1Resolve_productRoute
  '/docs/api/read-product': typeof DocsApiReadProductRoute
  '/docs/api/resolve-product': typeof DocsApiResolveProductRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/readability': typeof ReadabilityRoute
  '/takedown': typeof TakedownRoute
  '/terms': typeof TermsRoute
  '/about/bot': typeof AboutBotRoute
  '/api/capture': typeof ApiCaptureRoute
  '/api/check': typeof ApiCheckRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/takedown': typeof ApiTakedownRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/rate-limits': typeof DocsRateLimitsRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/why/$reason': typeof WhyReasonRoute
  '/docs': typeof DocsIndexRoute
  '/why': typeof WhyIndexRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/dashboard/metrics': typeof AuthenticatedDashboardMetricsRoute
  '/dashboard/usage': typeof AuthenticatedDashboardUsageRoute
  '/dashboard/waitlist': typeof AuthenticatedDashboardWaitlistRoute
  '/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/brief_product': typeof ApiV1Brief_productRoute
  '/api/v1/compare_products': typeof ApiV1Compare_productsRoute
  '/api/v1/read_product': typeof ApiV1Read_productRoute
  '/api/v1/report_outcome': typeof ApiV1Report_outcomeRoute
  '/api/v1/resolve_product': typeof ApiV1Resolve_productRoute
  '/docs/api/read-product': typeof DocsApiReadProductRoute
  '/docs/api/resolve-product': typeof DocsApiResolveProductRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/readability': typeof ReadabilityRoute
  '/takedown': typeof TakedownRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/about/bot': typeof AboutBotRoute
  '/api/capture': typeof ApiCaptureRoute
  '/api/check': typeof ApiCheckRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/takedown': typeof ApiTakedownRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/rate-limits': typeof DocsRateLimitsRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/why/$reason': typeof WhyReasonRoute
  '/docs/': typeof DocsIndexRoute
  '/why/': typeof WhyIndexRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/_authenticated/dashboard/metrics': typeof AuthenticatedDashboardMetricsRoute
  '/_authenticated/dashboard/usage': typeof AuthenticatedDashboardUsageRoute
  '/_authenticated/dashboard/waitlist': typeof AuthenticatedDashboardWaitlistRoute
  '/_authenticated/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/brief_product': typeof ApiV1Brief_productRoute
  '/api/v1/compare_products': typeof ApiV1Compare_productsRoute
  '/api/v1/read_product': typeof ApiV1Read_productRoute
  '/api/v1/report_outcome': typeof ApiV1Report_outcomeRoute
  '/api/v1/resolve_product': typeof ApiV1Resolve_productRoute
  '/docs/api/read-product': typeof DocsApiReadProductRoute
  '/docs/api/resolve-product': typeof DocsApiResolveProductRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/privacy'
    | '/readability'
    | '/takedown'
    | '/terms'
    | '/dashboard'
    | '/about/bot'
    | '/api/capture'
    | '/api/check'
    | '/api/health'
    | '/api/mcp'
    | '/api/takedown'
    | '/docs/errors'
    | '/docs/mcp'
    | '/docs/quickstart'
    | '/docs/rate-limits'
    | '/docs/webhooks'
    | '/why/$reason'
    | '/docs/'
    | '/why/'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/metrics'
    | '/dashboard/usage'
    | '/dashboard/waitlist'
    | '/dashboard/webhooks'
    | '/api/stripe/webhook'
    | '/api/v1/brief_product'
    | '/api/v1/compare_products'
    | '/api/v1/read_product'
    | '/api/v1/report_outcome'
    | '/api/v1/resolve_product'
    | '/docs/api/read-product'
    | '/docs/api/resolve-product'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/readability'
    | '/takedown'
    | '/terms'
    | '/about/bot'
    | '/api/capture'
    | '/api/check'
    | '/api/health'
    | '/api/mcp'
    | '/api/takedown'
    | '/docs/errors'
    | '/docs/mcp'
    | '/docs/quickstart'
    | '/docs/rate-limits'
    | '/docs/webhooks'
    | '/why/$reason'
    | '/docs'
    | '/why'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/metrics'
    | '/dashboard/usage'
    | '/dashboard/waitlist'
    | '/dashboard/webhooks'
    | '/api/stripe/webhook'
    | '/api/v1/brief_product'
    | '/api/v1/compare_products'
    | '/api/v1/read_product'
    | '/api/v1/report_outcome'
    | '/api/v1/resolve_product'
    | '/docs/api/read-product'
    | '/docs/api/resolve-product'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/docs'
    | '/privacy'
    | '/readability'
    | '/takedown'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/about/bot'
    | '/api/capture'
    | '/api/check'
    | '/api/health'
    | '/api/mcp'
    | '/api/takedown'
    | '/docs/errors'
    | '/docs/mcp'
    | '/docs/quickstart'
    | '/docs/rate-limits'
    | '/docs/webhooks'
    | '/why/$reason'
    | '/docs/'
    | '/why/'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/keys'
    | '/_authenticated/dashboard/metrics'
    | '/_authenticated/dashboard/usage'
    | '/_authenticated/dashboard/waitlist'
    | '/_authenticated/dashboard/webhooks'
    | '/api/stripe/webhook'
    | '/api/v1/brief_product'
    | '/api/v1/compare_products'
    | '/api/v1/read_product'
    | '/api/v1/report_outcome'
    | '/api/v1/resolve_product'
    | '/docs/api/read-product'
    | '/docs/api/resolve-product'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ReadabilityRoute: typeof ReadabilityRoute
  TakedownRoute: typeof TakedownRoute
  TermsRoute: typeof TermsRoute
  AboutBotRoute: typeof AboutBotRoute
  ApiCaptureRoute: typeof ApiCaptureRoute
  ApiCheckRoute: typeof ApiCheckRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiTakedownRoute: typeof ApiTakedownRoute
  WhyReasonRoute: typeof WhyReasonRoute
  WhyIndexRoute: typeof WhyIndexRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiV1Brief_productRoute: typeof ApiV1Brief_productRoute
  ApiV1Compare_productsRoute: typeof ApiV1Compare_productsRoute
  ApiV1Read_productRoute: typeof ApiV1Read_productRoute
  ApiV1Report_outcomeRoute: typeof ApiV1Report_outcomeRoute
  ApiV1Resolve_productRoute: typeof ApiV1Resolve_productRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takedown': {
      id: '/takedown'
      path: '/takedown'
      fullPath: '/takedown'
      preLoaderRoute: typeof TakedownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readability': {
      id: '/readability'
      path: '/readability'
      fullPath: '/readability'
      preLoaderRoute: typeof ReadabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why/': {
      id: '/why/'
      path: '/why'
      fullPath: '/why/'
      preLoaderRoute: typeof WhyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/why/$reason': {
      id: '/why/$reason'
      path: '/why/$reason'
      fullPath: '/why/$reason'
      preLoaderRoute: typeof WhyReasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/webhooks': {
      id: '/docs/webhooks'
      path: '/webhooks'
      fullPath: '/docs/webhooks'
      preLoaderRoute: typeof DocsWebhooksRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/rate-limits': {
      id: '/docs/rate-limits'
      path: '/rate-limits'
      fullPath: '/docs/rate-limits'
      preLoaderRoute: typeof DocsRateLimitsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/mcp': {
      id: '/docs/mcp'
      path: '/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof DocsMcpRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/errors': {
      id: '/docs/errors'
      path: '/errors'
      fullPath: '/docs/errors'
      preLoaderRoute: typeof DocsErrorsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/takedown': {
      id: '/api/takedown'
      path: '/api/takedown'
      fullPath: '/api/takedown'
      preLoaderRoute: typeof ApiTakedownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check': {
      id: '/api/check'
      path: '/api/check'
      fullPath: '/api/check'
      preLoaderRoute: typeof ApiCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capture': {
      id: '/api/capture'
      path: '/api/capture'
      fullPath: '/api/capture'
      preLoaderRoute: typeof ApiCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/bot': {
      id: '/about/bot'
      path: '/about/bot'
      fullPath: '/about/bot'
      preLoaderRoute: typeof AboutBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/docs/api/resolve-product': {
      id: '/docs/api/resolve-product'
      path: '/api/resolve-product'
      fullPath: '/docs/api/resolve-product'
      preLoaderRoute: typeof DocsApiResolveProductRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api/read-product': {
      id: '/docs/api/read-product'
      path: '/api/read-product'
      fullPath: '/docs/api/read-product'
      preLoaderRoute: typeof DocsApiReadProductRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/v1/resolve_product': {
      id: '/api/v1/resolve_product'
      path: '/api/v1/resolve_product'
      fullPath: '/api/v1/resolve_product'
      preLoaderRoute: typeof ApiV1Resolve_productRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/report_outcome': {
      id: '/api/v1/report_outcome'
      path: '/api/v1/report_outcome'
      fullPath: '/api/v1/report_outcome'
      preLoaderRoute: typeof ApiV1Report_outcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/read_product': {
      id: '/api/v1/read_product'
      path: '/api/v1/read_product'
      fullPath: '/api/v1/read_product'
      preLoaderRoute: typeof ApiV1Read_productRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/compare_products': {
      id: '/api/v1/compare_products'
      path: '/api/v1/compare_products'
      fullPath: '/api/v1/compare_products'
      preLoaderRoute: typeof ApiV1Compare_productsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/brief_product': {
      id: '/api/v1/brief_product'
      path: '/api/v1/brief_product'
      fullPath: '/api/v1/brief_product'
      preLoaderRoute: typeof ApiV1Brief_productRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/webhooks': {
      id: '/_authenticated/dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof AuthenticatedDashboardWebhooksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/waitlist': {
      id: '/_authenticated/dashboard/waitlist'
      path: '/waitlist'
      fullPath: '/dashboard/waitlist'
      preLoaderRoute: typeof AuthenticatedDashboardWaitlistRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/usage': {
      id: '/_authenticated/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof AuthenticatedDashboardUsageRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/metrics': {
      id: '/_authenticated/dashboard/metrics'
      path: '/metrics'
      fullPath: '/dashboard/metrics'
      preLoaderRoute: typeof AuthenticatedDashboardMetricsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/keys': {
      id: '/_authenticated/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof AuthenticatedDashboardKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardKeysRoute: typeof AuthenticatedDashboardKeysRoute
  AuthenticatedDashboardMetricsRoute: typeof AuthenticatedDashboardMetricsRoute
  AuthenticatedDashboardUsageRoute: typeof AuthenticatedDashboardUsageRoute
  AuthenticatedDashboardWaitlistRoute: typeof AuthenticatedDashboardWaitlistRoute
  AuthenticatedDashboardWebhooksRoute: typeof AuthenticatedDashboardWebhooksRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardKeysRoute: AuthenticatedDashboardKeysRoute,
    AuthenticatedDashboardMetricsRoute: AuthenticatedDashboardMetricsRoute,
    AuthenticatedDashboardUsageRoute: AuthenticatedDashboardUsageRoute,
    AuthenticatedDashboardWaitlistRoute: AuthenticatedDashboardWaitlistRoute,
    AuthenticatedDashboardWebhooksRoute: AuthenticatedDashboardWebhooksRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DocsRouteChildren {
  DocsErrorsRoute: typeof DocsErrorsRoute
  DocsMcpRoute: typeof DocsMcpRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsRateLimitsRoute: typeof DocsRateLimitsRoute
  DocsWebhooksRoute: typeof DocsWebhooksRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsApiReadProductRoute: typeof DocsApiReadProductRoute
  DocsApiResolveProductRoute: typeof DocsApiResolveProductRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsErrorsRoute: DocsErrorsRoute,
  DocsMcpRoute: DocsMcpRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsRateLimitsRoute: DocsRateLimitsRoute,
  DocsWebhooksRoute: DocsWebhooksRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsApiReadProductRoute: DocsApiReadProductRoute,
  DocsApiResolveProductRoute: DocsApiResolveProductRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ReadabilityRoute: ReadabilityRoute,
  TakedownRoute: TakedownRoute,
  TermsRoute: TermsRoute,
  AboutBotRoute: AboutBotRoute,
  ApiCaptureRoute: ApiCaptureRoute,
  ApiCheckRoute: ApiCheckRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiTakedownRoute: ApiTakedownRoute,
  WhyReasonRoute: WhyReasonRoute,
  WhyIndexRoute: WhyIndexRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiV1Brief_productRoute: ApiV1Brief_productRoute,
  ApiV1Compare_productsRoute: ApiV1Compare_productsRoute,
  ApiV1Read_productRoute: ApiV1Read_productRoute,
  ApiV1Report_outcomeRoute: ApiV1Report_outcomeRoute,
  ApiV1Resolve_productRoute: ApiV1Resolve_productRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
